// Generated from official lists; regenerate rather than hand-edit.
// delhi: Office of the District Magistrate, New Delhi, "STD & PIN Codes" (every row as published).
// others: India Post post-office directory, limited to pin codes inside each present-day district.

export type CityKey = 'delhi' | 'noida' | 'gurugram' | 'ghaziabad' | 'faridabad';

/** [pin code, place names] sorted by pin code, names A–Z. */
export const PIN_GROUPS: Record<CityKey, [string, string[]][]> = {
  delhi: [
    ["110001", ["Connaught Place", "Constitution House", "Eastern Court", "Election Commission", "Janpath", "Krishi Bhawan", "Lady Harding Medical College", "Laxminarain Mandir", "New Delhi G P O", "North Avenue", "Parliament House", "Parliament Street H O", "Patiala House", "Pragati Maidan", "Rail Bhawan", "Sansadiya Soudha", "Sectt North", "Shastri Bhawan", "Supreme Court"]],
    ["110002", ["A G C R", "Ajmeri Gate Extension", "Ansari Road", "Darya Ganj", "Gandhi Samarak", "Indian Agriculture", "Indraprastha Estate", "Indraprastha H O", "Minto Road", "Nidhi", "Rajghat Power House"]],
    ["110003", ["Aliganj", "Delhi High Court", "Golf Links", "Jawahar Lal Nehru Stadium", "Lodi Colony Market", "Lodi House Hostel", "Lodi Road H O", "Lok Nagar Bhawan", "Oberei Intercontinental", "Pandara Road", "Pragati Vihar", "Safdarjang Air Port", "Wazir Nagar"]],
    ["110004", ["Rashtrapati Bhawan"]],
    ["110005", ["Anand Nagar", "Anand Parbat", "Bank Street", "Desh Bandhu Gupta Road", "Guru Gobind Singh Marg", "Industrial Area", "Joshi Nagar", "Karol Bagh", "Lower Camp Anand Parbat", "Model Basti", "Sat Nahar", "Than Singh Nagar"]],
    ["110006", ["Bara Tooti", "Chandni Chowk", "Chawri Bazar", "Dareeba", "Delhi Cloth Mills", "Delhi G P O", "Delhi Sadar Bazar", "Farashkhana", "Fatehpuri", "Hamdard Dawakhana", "Hauz Qazi", "Idgah Road I S B T", "Jama Masjid", "Mori Gate", "Red Fort", "Sadar Thana Road"]],
    ["110007", ["Birla Lines", "C C Institute", "Delhi University", "Jawahar Nagar", "Kamla Nagar", "Lancer Road Market", "Lok Nayak Bhawan", "Malka Ganj", "Malka Ganj Market", "Partap Nagar", "Patrachar Road", "Patrachar Vidyala", "Pragati Vihar", "Rana Pratap Bagh", "Rly C A O", "Roop Nagar", "Roshan Area Road", "Safdarjang Air Port", "Sewa Sangh", "Shakti Nagar", "Subzi Mandi", "Timarpur", "Wazir Nagar"]],
    ["110008", ["Dada Ghosh Bhawan", "Patel Nagar", "Patel Nagar East", "Patel Nagar South", "Patel Nagar West"]],
    ["110010", ["A F Palam", "A P S Colony", "Army Base", "Bazar Road", "Central Ordinance", "Central Vehicle", "Delhi Cantt", "Depot", "Dhaula Khuan", "Kirby Place", "Work Shop"]],
    ["110011", ["Defence Head Qrs", "Gymkhana Club", "Nirman Bhawan", "Sectt South", "Shahjahan Road", "South Avenue", "U P S C", "Udyog Bhawan"]],
    ["110012", ["Central Tractor", "Inderpuri", "N P Laboratories", "Organisation", "Research Institute"]],
    ["110013", ["Dargah Shareef", "Hazrat Nizamuddin"]],
    ["110014", ["Hari Nagar Ashram", "Jangpura"]],
    ["110015", ["Central Kirti Nagar", "D I Area", "E S I Hospital", "Industrial Area", "Karampura", "Kirti Nagar", "Mansarover Garden", "Moti Nagar", "North Industrial Area", "Ramesh Nagar H O", "Sudershan Park", "Vishnu Garden", "Zakhira"]],
    ["110016", ["Ashram", "Green Park", "Green Park Market", "Hauz Khas", "Hauz Khas Market", "I I T Hauz Khas", "N I E Compus", "Shri Aurobindo", "Yusaf Sarai"]],
    ["110017", ["Malviya Nagar", "Panchseel Enclave", "Pushpa Vihar Sector I", "South Malviya Nagar"]],
    ["110018", ["Ashok Nagar", "Chand Nagar", "Fateh Nagar", "Khyalla Phase I", "Khyalla Phase II", "Mahabir Nagar", "Major Bhupinder Singh Nag", "Tihar", "Tilak Nagar", "Tilak Nagar East", "Vikaspuri", "Vishnu Garden"]],
    ["110019", ["Govindpuri", "Kalkaji", "Nehru Place"]],
    ["110020", ["C R R I", "Flatted Factories Complex", "Okhla Industrial Estate"]],
    ["110021", ["Anand Niketan", "Ashoka Hotel", "Chankyapuri", "Malcha Marg", "Moti Bagh", "Nanakpura"]],
    ["110022", ["Postal Saving Bureau", "R K Puram Sector I", "R K Puram Sector II", "R K Puram Sector III", "R K Puram Sector Iv", "R K Puram Sector IX", "R K Puram Sector VII", "R K Puram Sector VIII", "R K Puram Sector XII", "R K Puram V"]],
    ["110023", ["Kidwai Nagar", "Kidwai Nagar West", "Laxmi Bai Nagar", "Netaji Nagar", "Sarojini Nagar H O"]],
    ["110024", ["Amar Colony", "Defence Colony", "Krishna Market", "Lajpat Nagar"]],
    ["110025", ["Jamia Nagar", "Zakhir Nagar"]],
    ["110026", ["Punjabi Bagh", "Punjabi Bagh Sector Iii"]],
    ["110027", ["J 6 Block Rajouri Garden", "J J Colony", "Janta Market", "Najafgarh Road", "Rajouri Garden", "Rajouri Market", "Subhash Nagar", "Subhash Nagar West", "Tatarpur"]],
    ["110028", ["Naraina", "Naraina Industrial Estate", "Naraina Vihar"]],
    ["110029", ["Himayunpur Extn", "Nauroji Nagar", "Safdarjang Enclave"]],
    ["110030", ["Mehrauli", "T B Hospital"]],
    ["110031", ["Gandhi Nagar", "Gandhi Nagar Bazar", "Geeta Colony", "Kailash Nagar", "Raghubarpura", "Sahstri Nagar"]],
    ["110032", ["Balbir Nagar", "Bhola Nath Nagar", "Dilshad Garden", "Kabool Nagar", "Loni Road", "Mansarover Park", "New Seemapuri", "Rohtash Nagar", "Seemapuri Old", "Shahdara", "Shahdara Mandi", "Teliwara", "Vishwa Karma Nagar", "Vishwan Nagar", "Vivek Vihar"]],
    ["110033", ["A T Mills", "Adarsh Nagar", "Bhaiparma Nand Nagar", "G T S Nagar", "Gujranwala Nagar Part Ii", "Harijan Sewak Sangh", "Jahangirpuri Block A", "Jahangirpuri Block D", "Jahangirpuri Block H", "Jaroda Majra", "Model Town A Block", "Model Town II", "Mukerjee Nagar", "New Sabzi Mandi", "Nirankari Colony", "Shalimar Bagh", "Suraj Nagar", "Vijay Nagar"]],
    ["110034", ["Anandvas Shakurpur", "Multani Mohalla", "Pitampura", "Rani Bagh", "Saraswati Vihar", "Shakurbasti R S", "Shakurpur Block I", "Srinagar Colony"]],
    ["110035", ["Ganeshpuri", "Inderlok", "Lawrence Road", "Lekhu Nagar", "Onkar Nagar", "Power House", "Sarai Rohila"]],
    ["110036", ["Alipur", "Nangli Poona"]],
    ["110037", ["Gurgaon Road"]],
    ["110038", ["A F Rajokari"]],
    ["110039", ["Bawana"]],
    ["110040", ["Narela", "Narela Town", "Sanoth"]],
    ["110041", ["Budh Nagar", "Jawalpuri", "Nagloi", "Nangloi Phase III", "Sultanpuri Block C", "Sultanpuri Block F", "Suttanpuri Block B"]],
    ["110042", ["Badli", "Haiderpur", "Sameypur Badli"]],
    ["110043", ["Najafgarh"]],
    ["110044", ["Badarpur", "Badarpur T P Station", "Tughlakabad", "Tughlakabad A F Station"]],
    ["110045", ["Ambrohi", "Bakrola", "Palam", "Palam Enclave"]],
    ["110046", ["Nangal Rava"]],
    ["110047", ["Arjan Garh"]],
    ["110048", ["Greater Kailash", "Greater Kailash Ii", "Kailash", "Kailash Colony", "Masjidmoth Phase II", "N Block Greater"]],
    ["110049", ["Andrews Ganj", "Asian Games Village", "Guatam Nagar", "Gulmohar Park", "Masjid Moth Extn", "Sadiq Nagar", "South Extn Part I", "South Extn Part II"]],
    ["110051", ["Anarkali", "Azad Nagar", "Gobindpura", "Krishan Nagar Bazar", "Krishan Nagar H O", "Lajpat Rai Chowk", "Radheypuri", "Ram Nagar"]],
    ["110052", ["Ashok Vihar H O", "Bharat Nagar", "Nimri", "Satyawati Nagar", "Shastri Nagar", "Wazirpur Phase III"]],
    ["110053", ["Bhajanpuri", "Brahampuri", "Jagjit Nagar", "Maujpur", "Seelampur", "Yamuna Vihar", "Zafrabad"]],
    ["110054", ["C R P F Camp", "Civil Lines", "Distt Courts", "Maidens Hotel"]],
    ["110055", ["Amrit Kaur Market", "Multani Dhanda", "P S B Paharganj", "Paharganj", "Swami Ram Tirath Nagar"]],
    ["110056", ["Shakurbasti"]],
    ["110057", ["Munirka", "Vasant Vihar I", "Vasant Vihar II"]],
    ["110058", ["Janakpuri", "Janakpuri Block C 4", "Janakpuri Block D 1", "Janakpuri Blockc 2", "Possangipur"]],
    ["110059", ["Jeewan Park", "Uttam Nagar"]],
    ["110060", ["New Rajinder Nagar", "Rajinder Nagar", "Ravinder Rangsala"]],
    ["110061", ["Bijwasan"]],
    ["110062", ["Ambedkar Nagar", "B S F Camp Tigri", "Dakshimpuri Phase I", "Dakshinpuri Phase III", "Hamdard Nagar", "Khanpur", "Madangir", "Pushpa Bhawan"]],
    ["110063", ["Madipur", "Paschim Vihar", "Paschim Vihar Block B", "Qr Madipur"]],
    ["110064", ["Hari Nagar Be Block", "Hari Nagar Da & Db Block", "Mayapuri", "Mayapuri Shopping Centre"]],
    ["110065", ["East Of Kailash", "Nehru Nagar", "Sriniwaspuri"]],
    ["110066", ["R K Puram", "R K Puram West"]],
    ["110067", ["D D A Munirka", "Jawahar Lal Nehru Univers"]],
    ["110071", ["Chhawla"]],
    ["110072", ["D D A Salam", "Jharoda Kalan", "P T S Jharoda Kalan"]],
    ["110073", ["Ujwa"]],
    ["110081", ["Kanjhawala"]],
    ["110082", ["Khera Kalan"]],
    ["110083", ["Mangolpuri", "Mangolpuri Block 1", "Mangolpuri Block A", "Mangolpuri Block S"]],
    ["110084", ["Kutubgarh"]],
    ["110091", ["Himmatpuri", "Kalyanpuri", "Khichripur", "Trilokpuri"]],
    ["110092", ["Kalyan Vas", "Laxmi Nagar Market", "Patper Ganj", "Shakarpur"]],
    ["110093", ["Nand Nagri", "Nand Nagri A Block", "Nathu Colony"]],
    ["110094", ["Chilla Villege", "Gokulpuri", "Karawal Nagar"]],
    ["110096", ["Bhajan Pura"]],
  ],
  noida: [
    ["201008", ["Bisara", "Piyaoli", "Salarpur Kalan", "Vidyut Nagar"]],
    ["201301", ["Noida", "Noida Sector 12", "Noida Sector 16", "Noida Sector 27"]],
    ["201303", ["Noida Sector 30", "Noida Sector 37", "Noida Sector 41", "Noida Sector 45"]],
    ["201304", ["Baraula", "Chhaprauli Bengar", "Gejha", "Maharishi Nagar"]],
    ["201305", ["Nagla Charandas", "Nepz Post Office"]],
    ["201306", ["Bisrakh", "I.A. Surajpur", "Kulesra", "Sakipur", "Tilapta Karanwas"]],
    ["201307", ["Chhajarsi", "Noida Sector 34", "Noida Sector 55", "Parthala Khanjarpur", "Sarfabad"]],
    ["201309", ["Khora Gaon", "Noida Sector 62"]],
    ["201310", ["Alpha Greater Noida", "Ghori", "Kasna", "Knowledge Park-I", "Maicha", "Tugalpur"]],
    ["201311", ["Container Depot"]],
    ["201312", ["Gautam Budh University"]],
    ["201313", ["Amity University"]],
    ["201314", ["Chhaisa", "Chholas", "Chithera", "Khandera", "Kot", "Luharli", "Sainthli", "Shiv Nadar University"]],
    ["203135", ["Dayanatpur", "Faleda", "Jewar", "Kanigarhi", "Kureb", "Mangrouly", "Sabouta Jafrabad"]],
    ["203141", ["Bhunna Jattan", "Chhapana", "Chingrawly", "Gotheny", "Hasanpur", "Jahangirpur", "Jawan", "Lodana", "Mansoor Pur Hasanpur", "Narmohamadpur"]],
    ["203155", ["Bankapur", "Chanchaly", "Kishore Pur", "Manchad", "Neemka", "Ranhera", "Thora"]],
    ["203201", ["Dhanouri Kalan", "Nawada", "Parsol"]],
    ["203202", ["Astauly", "Baroda", "Chiti", "Deota", "Rashol Rithaury", "Salempur Gujar", "Wair"]],
    ["203207", ["Achheja", "Bambawar", "Behhrampur", "Dadri", "Dhoomedso", "Dujana", "Jarcha", "Kachera Versabad", "Kalaunda", "Khatana", "Kheri Bhanauta", "Pali", "Vedpura"]],
    ["203209", ["Bhaipur Brahmanan", "Karauli Banger", "Rabupura", "Ronija", "Tirthaly"]],
  ],
  gurugram: [
    ["122001", ["Arjun Nagar", "Basai Road", "Gurgaon", "Gurgaon Kty.", "Gurgaon Sector 17", "Gurgaon South City I", "Khandsa Road", "Mini Sectt.", "New Colony", "Shivaji Nagar", "Sohna Adda", "Urban Estate"]],
    ["122002", ["Chakkarpur", "DLF QE", "Nathupur"]],
    ["122003", ["Gurgaon Sector 45", "Gwal Pahari", "Jharsa", "Smaspur", "Wazirabad"]],
    ["122004", ["Khandsa", "Kherki Daula", "Lakhnaula", "Narsinghpur", "Sikanderpur", "Sikohpur"]],
    ["122005", ["Air Force"]],
    ["122006", ["Basai", "Daultabad", "Gurgaon Village", "Railwary Road"]],
    ["122007", ["Industrial Estate"]],
    ["122008", ["DLF Ph-II"]],
    ["122009", ["Galleria DLF-IV"]],
    ["122010", ["DLF Ph-III"]],
    ["122011", ["Gurgaon Sector 56"]],
    ["122015", ["Palam Road", "Sarhaul"]],
    ["122016", ["Dundahera", "Industrial Complex Dundahera"]],
    ["122017", ["Carterpuri", "Palam Vihar"]],
    ["122018", ["Gurgaon South City II"]],
    ["122051", ["Kasan", "Manesar", "Nsg Camp Manesar"]],
    ["122052", ["IMT Manesar"]],
    ["122101", ["Badshahpur", "Fazilpur", "Kadipur", "Paltra", "Teekli"]],
    ["122102", ["Bhondsi", "Damdama", "Ghamroj", "Kherla", "Maruthi Kunj", "Raisina", "Rithoj"]],
    ["122103", ["Bhirauti", "Chapera", "Daulah", "Ghasera", "Ghungola", "Indir Mewat", "KherliLala", "Kiranj", "Rewasan", "Rojka Meo", "Sohna"]],
    ["122413", ["Bhorakalan", "Bilaspur Khurd", "Dhani Chitarsain", "Moklawas", "Pachgaon", "Pathreri", "Sidhrawali"]],
    ["122414", ["Inchhapuri", "Khatauli", "Khor", "Lokra", "Nanukalan", "Syed Shahpur"]],
    ["122502", ["Cheelarh", "Jagat", "Jaitpur", "Jant", "Kakoria", "Khalilpur", "Mirpur", "Pahari", "Ramgarh", "Sherpur", "Tatarpur", "Turkiawas"]],
    ["122503", ["Baslambi", "Baspadamka", "Jamalpur", "Janaula", "Narhera", "Pataudi", "Unchamajra"]],
    ["122504", ["Haillymandi", "Jataula", "Jatauli", "Karola", "Khandewia", "Mehchana", "Noorgarh"]],
    ["122505", ["Bhangrola", "Budhera", "Dhankot", "Garhi Harsaru", "Mankdola", "Wazipur"]],
    ["122506", ["Farrukh Nagar", "Khera Khurampur", "Patil R.S.", "Sewari", "Sultanpur"]],
  ],
  ghaziabad: [
    ["201001", ["Ashok Nagar", "Ghaziabad", "Nehru Nagar", "Ramte Ram Road"]],
    ["201002", ["Ingram Institute", "Kamla Nehru Nagar", "Kavi Nagar", "New Raj Nagar", "Old Raj Nagar", "Police Line Harsaon", "Raispur", "Rajapur", "RAKNPA", "Sadarpur", "Shahpur Bamheta", "Shastri Nagar", "Vivekanand Nagar"]],
    ["201003", ["Ator Nagla", "Aurangabad Ristal", "Bhup Kheri", "Farrukh Nagar", "Meerut Road", "Morta", "Nistoli"]],
    ["201004", ["Hindon Air Field"]],
    ["201005", ["Bhopura", "Pasonda", "Sahibabad"]],
    ["201006", ["Chikamberpur"]],
    ["201007", ["Mohan Nagar"]],
    ["201009", ["Arya Nagar", "B.B.Nagar", "Chhaprola", "Chhipyana", "Dasna Gate Ed", "Dundahera", "Ghaziabad City", "Kaila", "Model Town", "Nasratpura ED", "Roza Yakubpur", "Vijai Nagar"]],
    ["201010", ["Bharat Nagar", "Hasanpur Bhowapur", "I.E.Sahibabad"]],
    ["201011", ["Chander Nagar"]],
    ["201012", ["Kaushambi", "Vasundhra"]],
    ["201013", ["Govindpuram"]],
    ["201014", ["Makanpur", "Shipra Sun City"]],
    ["201015", ["Adhyatmic Nagar", "Dasna", "Dasna R.S.", "Galand", "Hassanpur", "Hindan Nagar", "Jindal Nagar", "Kushlia", "Nahal", "Udai Rampur Nagla"]],
    ["201016", ["Crossing Republik"]],
    ["201017", ["Raj Nagar Extension"]],
    ["201019", ["Vaishali"]],
    ["201102", ["Badshahnpur Siroli", "Behta Hazipur", "Chirori", "Jaoli", "Loni", "Mandola", "Teela Sahbazpur"]],
    ["201103", ["Tronica City"]],
    ["201201", ["Churiyala", "Govindpuri", "Harmukhpuri", "Rori", "Saidpur", "Sara", "Talhata"]],
    ["201204", ["Begmabad", "Gyaspur", "Khanjarpur", "Khindora", "Modi Nagar", "Nagla Akhu", "Niwari", "Painga", "Patla", "Saunda", "Shahjahanpur", "Sikri Kalan", "Sikri Khurd", "Tibra"]],
    ["201206", ["Abupur", "Basantpur Sainthli", "Bhadoli", "Bhikanpur", "Didoli", "Dosa Banjarpur", "Duhai", "Jalalabad", "Jalalpur Dhindar", "Kakra", "Kanauja", "Khimawati", "Kumhera", "Murad Nagar", "Murad Nagar Bazar", "Murad Nagar Town", "Nekpur", "Noorpur", "Raoli Kalan", "Shahpur", "Sultanpur", "Surana"]],
  ],
  faridabad: [
    ["121001", ["Factory Area Faridabad", "Faridabad NIT", "Feroz Gandhi Nagar Faridabad", "Industrial Area Faridabad", "N.I.F.M. Faridabad", "Nh-2 Faridabad", "Nh-3 Faridabad", "Nh-4 Faridabad"]],
    ["121002", ["Bhaskola", "Faridabad City", "Faridabad Sector 16", "Faridabad Sector 16a", "Faridabad Sector 18", "Kheri Kalan"]],
    ["121003", ["Amarnagar", "Anangpur", "Gurukul Indraprashtha", "Mathura Road Faridabad", "Tilpat"]],
    ["121004", ["Amarpur", "Atali", "Ballabgarh", "Baroli", "Chawla Colony Ballabgarh", "Chhainsa", "Dayalpur", "Deeg", "Dhauj", "E C Dhauj", "Faridabad Sector 3", "Fatehpur Billoch", "Fatehpur Tagga", "Gadpuri", "Gonchhi", "Jawan", "Machhgar", "Mohna", "N.T.P.C./sector-10 Faridabad", "Neemka", "Pali", "Panhera Khurd", "Sagarpur", "Seekri"]],
    ["121005", ["Faridabad Sector 22", "Jawahar Colony Faridabad"]],
    ["121006", ["Faridabad Sector 7", "Faridabad Sector 8", "Faridabad Sector 9", "G.T. Road Faridabad"]],
    ["121007", ["Escortsnagar Faridabad", "Faridabad Sector 12", "Faridabad Sector 15"]],
    ["121008", ["Faridabad Sector 29"]],
    ["121009", ["Surajkund Faridabad"]],
    ["121010", ["Nhpc Colony Faridabad"]],
    ["121012", ["Sector-21D"]],
    ["121013", ["Sec-91"]],
    ["121101", ["Alipur", "Badarpur Syed", "Bhainsrawali", "Bhuvapur", "Chandpur", "Faridpur", "Kurali", "Manjhawali", "Tigaon"]],
  ],
};
