// Generated by `supabase gen types typescript` from the migrated schema
// (supabase/migrations 090012–090014). Regenerate after every migration:
//   npx supabase gen types typescript --linked --schema public > src/lib/database.types.ts
// then re-append the aliases at the bottom.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string;
          actor_id: string | null;
          created_at: string;
          detail: NonNullable<Json>;
          entity: string;
          entity_id: string | null;
          id: number;
        };
        Insert: {
          action: string;
          actor_id?: string | null;
          created_at?: string;
          detail?: NonNullable<Json>;
          entity: string;
          entity_id?: string | null;
          id?: number;
        };
        Update: {
          action?: string;
          actor_id?: string | null;
          created_at?: string;
          detail?: NonNullable<Json>;
          entity?: string;
          entity_id?: string | null;
          id?: number;
        };
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      call_logs: {
        Row: {
          actor_id: string | null;
          channel: Database["public"]["Enums"]["contact_channel"];
          created_at: string;
          id: string;
          lead_id: string;
          logged_at: string | null;
          lost_reason: Database["public"]["Enums"]["lost_reason"] | null;
          note: string | null;
          outcome: Database["public"]["Enums"]["connect_outcome"] | null;
          phone_e164: string | null;
          phone_id: string | null;
          result: Database["public"]["Enums"]["attempt_result"] | null;
          started_at: string;
          task_id: string | null;
        };
        Insert: {
          actor_id?: string | null;
          channel: Database["public"]["Enums"]["contact_channel"];
          created_at?: string;
          id?: string;
          lead_id: string;
          logged_at?: string | null;
          lost_reason?: Database["public"]["Enums"]["lost_reason"] | null;
          note?: string | null;
          outcome?: Database["public"]["Enums"]["connect_outcome"] | null;
          phone_e164?: string | null;
          phone_id?: string | null;
          result?: Database["public"]["Enums"]["attempt_result"] | null;
          started_at?: string;
          task_id?: string | null;
        };
        Update: {
          actor_id?: string | null;
          channel?: Database["public"]["Enums"]["contact_channel"];
          created_at?: string;
          id?: string;
          lead_id?: string;
          logged_at?: string | null;
          lost_reason?: Database["public"]["Enums"]["lost_reason"] | null;
          note?: string | null;
          outcome?: Database["public"]["Enums"]["connect_outcome"] | null;
          phone_e164?: string | null;
          phone_id?: string | null;
          result?: Database["public"]["Enums"]["attempt_result"] | null;
          started_at?: string;
          task_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "call_logs_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "call_logs_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "call_logs_phone_id_fkey";
            columns: ["phone_id"];
            isOneToOne: false;
            referencedRelation: "lead_phones";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "call_logs_task_id_fkey";
            columns: ["task_id"];
            isOneToOne: false;
            referencedRelation: "lead_tasks";
            referencedColumns: ["id"];
          },
        ];
      };
      crm_settings: {
        Row: {
          default_daily_quota: number;
          id: number;
          idle_timeout_minutes: number;
          nurture_after_misses: number;
          nurture_days: number;
          quote_follow_up_days: number;
          re_engage_days: number;
          retry_busy_minutes: number;
          retry_no_answer_minutes: number;
          retry_rejected_minutes: number;
          retry_unreachable_minutes: number;
          updated_at: string;
        };
        Insert: {
          default_daily_quota?: number;
          id?: number;
          idle_timeout_minutes?: number;
          nurture_after_misses?: number;
          nurture_days?: number;
          quote_follow_up_days?: number;
          re_engage_days?: number;
          retry_busy_minutes?: number;
          retry_no_answer_minutes?: number;
          retry_rejected_minutes?: number;
          retry_unreachable_minutes?: number;
          updated_at?: string;
        };
        Update: {
          default_daily_quota?: number;
          id?: number;
          idle_timeout_minutes?: number;
          nurture_after_misses?: number;
          nurture_days?: number;
          quote_follow_up_days?: number;
          re_engage_days?: number;
          retry_busy_minutes?: number;
          retry_no_answer_minutes?: number;
          retry_rejected_minutes?: number;
          retry_unreachable_minutes?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      inbound_enquiries: {
        Row: {
          best_time: string | null;
          converted_lead_id: string | null;
          created_at: string;
          email: string | null;
          id: string;
          kind: string;
          message: string | null;
          name: string;
          phone: string | null;
          user_agent: string | null;
        };
        Insert: {
          best_time?: string | null;
          converted_lead_id?: string | null;
          created_at?: string;
          email?: string | null;
          id?: string;
          kind: string;
          message?: string | null;
          name: string;
          phone?: string | null;
          user_agent?: string | null;
        };
        Update: {
          best_time?: string | null;
          converted_lead_id?: string | null;
          created_at?: string;
          email?: string | null;
          id?: string;
          kind?: string;
          message?: string | null;
          name?: string;
          phone?: string | null;
          user_agent?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "inbound_enquiries_converted_lead_id_fkey";
            columns: ["converted_lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      keepalive: {
        Row: {
          id: number;
          pinged_at: string;
          source: string | null;
        };
        Insert: {
          id?: number;
          pinged_at?: string;
          source?: string | null;
        };
        Update: {
          id?: number;
          pinged_at?: string;
          source?: string | null;
        };
        Relationships: [];
      };
      lead_activities: {
        Row: {
          actor_id: string | null;
          created_at: string;
          detail: NonNullable<Json>;
          id: string;
          kind: string;
          lead_id: string;
        };
        Insert: {
          actor_id?: string | null;
          created_at?: string;
          detail?: NonNullable<Json>;
          id?: string;
          kind: string;
          lead_id: string;
        };
        Update: {
          actor_id?: string | null;
          created_at?: string;
          detail?: NonNullable<Json>;
          id?: string;
          kind?: string;
          lead_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "lead_activities_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lead_activities_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      lead_contacts: {
        Row: {
          created_at: string;
          designation: string | null;
          email: string | null;
          id: string;
          is_primary: boolean;
          lead_id: string;
          name: string;
          sort_order: number;
        };
        Insert: {
          created_at?: string;
          designation?: string | null;
          email?: string | null;
          id?: string;
          is_primary?: boolean;
          lead_id: string;
          name: string;
          sort_order?: number;
        };
        Update: {
          created_at?: string;
          designation?: string | null;
          email?: string | null;
          id?: string;
          is_primary?: boolean;
          lead_id?: string;
          name?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "lead_contacts_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      lead_phones: {
        Row: {
          contact_id: string | null;
          created_at: string;
          id: string;
          is_invalid: boolean;
          is_primary: boolean;
          label: string | null;
          lead_id: string;
          no_whatsapp: boolean;
          phone_e164: string;
          sort_order: number;
        };
        Insert: {
          contact_id?: string | null;
          created_at?: string;
          id?: string;
          is_invalid?: boolean;
          is_primary?: boolean;
          label?: string | null;
          lead_id: string;
          no_whatsapp?: boolean;
          phone_e164: string;
          sort_order?: number;
        };
        Update: {
          contact_id?: string | null;
          created_at?: string;
          id?: string;
          is_invalid?: boolean;
          is_primary?: boolean;
          label?: string | null;
          lead_id?: string;
          no_whatsapp?: boolean;
          phone_e164?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "lead_phones_contact_id_fkey";
            columns: ["contact_id"];
            isOneToOne: false;
            referencedRelation: "lead_contacts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lead_phones_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      lead_tasks: {
        Row: {
          assignee_id: string | null;
          completed_at: string | null;
          completed_by: string | null;
          created_at: string;
          created_by: string | null;
          due_at: string;
          id: string;
          lead_id: string;
          location: string | null;
          meeting_mode: Database["public"]["Enums"]["meeting_mode"] | null;
          note: string | null;
          reschedule_count: number;
          result: string | null;
          status: Database["public"]["Enums"]["task_status"];
          type: Database["public"]["Enums"]["task_type"];
        };
        Insert: {
          assignee_id?: string | null;
          completed_at?: string | null;
          completed_by?: string | null;
          created_at?: string;
          created_by?: string | null;
          due_at: string;
          id?: string;
          lead_id: string;
          location?: string | null;
          meeting_mode?: Database["public"]["Enums"]["meeting_mode"] | null;
          note?: string | null;
          reschedule_count?: number;
          result?: string | null;
          status?: Database["public"]["Enums"]["task_status"];
          type: Database["public"]["Enums"]["task_type"];
        };
        Update: {
          assignee_id?: string | null;
          completed_at?: string | null;
          completed_by?: string | null;
          created_at?: string;
          created_by?: string | null;
          due_at?: string;
          id?: string;
          lead_id?: string;
          location?: string | null;
          meeting_mode?: Database["public"]["Enums"]["meeting_mode"] | null;
          note?: string | null;
          reschedule_count?: number;
          result?: string | null;
          status?: Database["public"]["Enums"]["task_status"];
          type?: Database["public"]["Enums"]["task_type"];
        };
        Relationships: [
          {
            foreignKeyName: "lead_tasks_assignee_id_fkey";
            columns: ["assignee_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lead_tasks_completed_by_fkey";
            columns: ["completed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lead_tasks_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lead_tasks_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      leads: {
        Row: {
          address: string | null;
          assigned_at: string | null;
          attempt_count: number;
          brand_name: string;
          competitor_contract_end: string | null;
          competitor_name: string | null;
          created_at: string;
          created_by: string | null;
          deal_value_inr: number | null;
          deleted_at: string | null;
          dnc: boolean;
          dnc_at: string | null;
          expected_delivery_date: string | null;
          id: string;
          instagram_username: string | null;
          last_attempt_at: string | null;
          last_connected_at: string | null;
          lead_found_on: string;
          lost_note: string | null;
          lost_reason: Database["public"]["Enums"]["lost_reason"] | null;
          next_action_at: string | null;
          next_action_type: Database["public"]["Enums"]["task_type"] | null;
          notes: string | null;
          owner_id: string | null;
          project_end_date: string | null;
          project_start_date: string | null;
          source: Database["public"]["Enums"]["lead_source"];
          stage: Database["public"]["Enums"]["lead_stage"];
          stage_changed_at: string;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          address?: string | null;
          assigned_at?: string | null;
          attempt_count?: number;
          brand_name: string;
          competitor_contract_end?: string | null;
          competitor_name?: string | null;
          created_at?: string;
          created_by?: string | null;
          deal_value_inr?: number | null;
          deleted_at?: string | null;
          dnc?: boolean;
          dnc_at?: string | null;
          expected_delivery_date?: string | null;
          id?: string;
          instagram_username?: string | null;
          last_attempt_at?: string | null;
          last_connected_at?: string | null;
          lead_found_on?: string;
          lost_note?: string | null;
          lost_reason?: Database["public"]["Enums"]["lost_reason"] | null;
          next_action_at?: string | null;
          next_action_type?: Database["public"]["Enums"]["task_type"] | null;
          notes?: string | null;
          owner_id?: string | null;
          project_end_date?: string | null;
          project_start_date?: string | null;
          source?: Database["public"]["Enums"]["lead_source"];
          stage?: Database["public"]["Enums"]["lead_stage"];
          stage_changed_at?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          address?: string | null;
          assigned_at?: string | null;
          attempt_count?: number;
          brand_name?: string;
          competitor_contract_end?: string | null;
          competitor_name?: string | null;
          created_at?: string;
          created_by?: string | null;
          deal_value_inr?: number | null;
          deleted_at?: string | null;
          dnc?: boolean;
          dnc_at?: string | null;
          expected_delivery_date?: string | null;
          id?: string;
          instagram_username?: string | null;
          last_attempt_at?: string | null;
          last_connected_at?: string | null;
          lead_found_on?: string;
          lost_note?: string | null;
          lost_reason?: Database["public"]["Enums"]["lost_reason"] | null;
          next_action_at?: string | null;
          next_action_type?: Database["public"]["Enums"]["task_type"] | null;
          notes?: string | null;
          owner_id?: string | null;
          project_end_date?: string | null;
          project_start_date?: string | null;
          source?: Database["public"]["Enums"]["lead_source"];
          stage?: Database["public"]["Enums"]["lead_stage"];
          stage_changed_at?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "leads_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "leads_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "leads_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      login_throttle: {
        Row: {
          fail_count: number;
          first_fail_at: string;
          key: string;
          locked_until: string | null;
        };
        Insert: {
          fail_count?: number;
          first_fail_at?: string;
          key: string;
          locked_until?: string | null;
        };
        Update: {
          fail_count?: number;
          first_fail_at?: string;
          key?: string;
          locked_until?: string | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          address: string | null;
          created_at: string;
          created_by: string | null;
          daily_lead_quota: number | null;
          email: string;
          full_name: string | null;
          id: string;
          is_active: boolean;
          last_top_up_on: string | null;
          phone: string | null;
          role: Database["public"]["Enums"]["app_role"];
          updated_at: string;
        };
        Insert: {
          address?: string | null;
          created_at?: string;
          created_by?: string | null;
          daily_lead_quota?: number | null;
          email?: string;
          full_name?: string | null;
          id: string;
          is_active?: boolean;
          last_top_up_on?: string | null;
          phone?: string | null;
          role?: Database["public"]["Enums"]["app_role"];
          updated_at?: string;
        };
        Update: {
          address?: string | null;
          created_at?: string;
          created_by?: string | null;
          daily_lead_quota?: number | null;
          email?: string;
          full_name?: string | null;
          id?: string;
          is_active?: boolean;
          last_top_up_on?: string | null;
          phone?: string | null;
          role?: Database["public"]["Enums"]["app_role"];
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      quotations: {
        Row: {
          amount_inr: number;
          decided_at: string | null;
          decision_reason: Database["public"]["Enums"]["lost_reason"] | null;
          id: string;
          lead_id: string;
          link: string | null;
          note: string | null;
          sent_at: string;
          sent_by: string | null;
          services: string | null;
          status: Database["public"]["Enums"]["quote_status"];
          valid_until: string | null;
          version: number;
        };
        Insert: {
          amount_inr: number;
          decided_at?: string | null;
          decision_reason?: Database["public"]["Enums"]["lost_reason"] | null;
          id?: string;
          lead_id: string;
          link?: string | null;
          note?: string | null;
          sent_at?: string;
          sent_by?: string | null;
          services?: string | null;
          status?: Database["public"]["Enums"]["quote_status"];
          valid_until?: string | null;
          version: number;
        };
        Update: {
          amount_inr?: number;
          decided_at?: string | null;
          decision_reason?: Database["public"]["Enums"]["lost_reason"] | null;
          id?: string;
          lead_id?: string;
          link?: string | null;
          note?: string | null;
          sent_at?: string;
          sent_by?: string | null;
          services?: string | null;
          status?: Database["public"]["Enums"]["quote_status"];
          valid_until?: string | null;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "quotations_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quotations_sent_by_fkey";
            columns: ["sent_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      _activity: {
        Args: { p_detail: Json; p_kind: string; p_lead: string };
        Returns: undefined;
      };
      _advance_stage: {
        Args: {
          p_lead: string;
          p_target: Database["public"]["Enums"]["lead_stage"];
        };
        Returns: undefined;
      };
      _audit: {
        Args: {
          p_action: string;
          p_detail: Json;
          p_entity: string;
          p_id: string;
        };
        Returns: undefined;
      };
      _close_tasks: {
        Args: {
          p_lead: string;
          p_only?: string;
          p_result: string;
          p_status: Database["public"]["Enums"]["task_status"];
          p_types?: Database["public"]["Enums"]["task_type"][];
        };
        Returns: undefined;
      };
      _create_quote: {
        Args: {
          p_amount: number;
          p_lead: string;
          p_link: string;
          p_services: string;
          p_valid: string;
        };
        Returns: string;
      };
      _internal_on: { Args: Record<PropertyKey, never>; Returns: undefined };
      _ist_today: { Args: Record<PropertyKey, never>; Returns: string };
      _mark_lost: {
        Args: {
          p_competitor?: string;
          p_contract_end?: string;
          p_lead: string;
          p_note: string;
          p_reason: Database["public"]["Enums"]["lost_reason"];
        };
        Returns: undefined;
      };
      _new_task: {
        Args: {
          p_due: string;
          p_lead: string;
          p_location?: string;
          p_mode?: Database["public"]["Enums"]["meeting_mode"];
          p_note?: string;
          p_type: Database["public"]["Enums"]["task_type"];
        };
        Returns: string;
      };
      _refresh_next_action: { Args: { p_lead: string }; Returns: undefined };
      _require_admin: { Args: Record<PropertyKey, never>; Returns: string };
      _require_lead: {
        Args: { p_lead: string };
        Returns: {
          address: string | null;
          assigned_at: string | null;
          attempt_count: number;
          brand_name: string;
          competitor_contract_end: string | null;
          competitor_name: string | null;
          created_at: string;
          created_by: string | null;
          deal_value_inr: number | null;
          deleted_at: string | null;
          dnc: boolean;
          dnc_at: string | null;
          expected_delivery_date: string | null;
          id: string;
          instagram_username: string | null;
          last_attempt_at: string | null;
          last_connected_at: string | null;
          lead_found_on: string;
          lost_note: string | null;
          lost_reason: Database["public"]["Enums"]["lost_reason"] | null;
          next_action_at: string | null;
          next_action_type: Database["public"]["Enums"]["task_type"] | null;
          notes: string | null;
          owner_id: string | null;
          project_end_date: string | null;
          project_start_date: string | null;
          source: Database["public"]["Enums"]["lead_source"];
          stage: Database["public"]["Enums"]["lead_stage"];
          stage_changed_at: string;
          updated_at: string;
          updated_by: string | null;
        };
        SetofOptions: {
          from: "*";
          to: "leads";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      _require_staff: { Args: Record<PropertyKey, never>; Returns: string };
      _set_stage: {
        Args: {
          p_lead: string;
          p_note?: string;
          p_reason?: Database["public"]["Enums"]["lost_reason"];
          p_stage: Database["public"]["Enums"]["lead_stage"];
        };
        Returns: undefined;
      };
      _stage_rank: {
        Args: { s: Database["public"]["Enums"]["lead_stage"] };
        Returns: number;
      };
      _top_up: {
        Args: { p_force: boolean; p_member: string };
        Returns: number;
      };
      _top_up_all: { Args: Record<PropertyKey, never>; Returns: number };
      add_note: {
        Args: { p_lead: string; p_text: string };
        Returns: undefined;
      };
      can_access_lead: { Args: { p_lead: string }; Returns: boolean };
      cancel_task: {
        Args: { p_reason: string; p_task: string };
        Returns: undefined;
      };
      complete_meeting: {
        Args: { p_task: string; payload: Json };
        Returns: Json;
      };
      create_lead_with_contacts: { Args: { payload: Json }; Returns: string };
      create_quotation: {
        Args: {
          p_amount: number;
          p_lead: string;
          p_link?: string;
          p_services?: string;
          p_valid_until: string;
        };
        Returns: string;
      };
      crm_dashboard: { Args: Record<PropertyKey, never>; Returns: Json };
      crm_insights: {
        Args: { p_from: string; p_member?: string; p_to: string };
        Returns: Json;
      };
      current_app_role: {
        Args: Record<PropertyKey, never>;
        Returns: Database["public"]["Enums"]["app_role"];
      };
      decide_quotation: {
        Args: {
          p_decision: string;
          p_note?: string;
          p_quote: string;
          p_reason?: Database["public"]["Enums"]["lost_reason"];
        };
        Returns: undefined;
      };
      discard_attempt: { Args: { p_attempt: string }; Returns: undefined };
      find_duplicates: {
        Args: { p_exclude?: string; p_handle: string; p_phones: string[] };
        Returns: {
          brand_name: string;
          can_open: boolean;
          lead_id: string;
          match: string;
          owner_name: string;
        }[];
      };
      import_leads: { Args: { p_rows: Json }; Returns: Json };
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_staff: { Args: Record<PropertyKey, never>; Returns: boolean };
      log_export: {
        Args: { p_count: number; p_filters: Json };
        Returns: undefined;
      };
      log_outcome: {
        Args: { p_attempt: string; payload: Json };
        Returns: Json;
      };
      normalize_instagram: { Args: { raw: string }; Returns: string };
      normalize_phone: { Args: { raw: string }; Returns: string };
      ping_keepalive: { Args: Record<PropertyKey, never>; Returns: undefined };
      reassign_leads: {
        Args: { p_leads: string[]; p_owner: string };
        Returns: number;
      };
      reschedule_task: {
        Args: { p_due: string; p_reason: string; p_task: string };
        Returns: undefined;
      };
      schedule_task: {
        Args: {
          p_due: string;
          p_lead: string;
          p_location?: string;
          p_mode?: Database["public"]["Enums"]["meeting_mode"];
          p_note?: string;
          p_type: Database["public"]["Enums"]["task_type"];
        };
        Returns: string;
      };
      set_lead_stage: {
        Args: {
          p_lead: string;
          p_note?: string;
          p_reason?: Database["public"]["Enums"]["lost_reason"];
          p_stage: Database["public"]["Enums"]["lead_stage"];
        };
        Returns: undefined;
      };
      set_member_quota: {
        Args: { p_member: string; p_quota: number };
        Returns: undefined;
      };
      start_attempt: {
        Args: {
          p_channel: Database["public"]["Enums"]["contact_channel"];
          p_lead: string;
          p_phone: string;
          p_task?: string;
        };
        Returns: string;
      };
      top_up_leads: { Args: { p_member?: string }; Returns: number };
      update_lead_with_contacts: {
        Args: { p_lead_id: string; payload: Json };
        Returns: undefined;
      };
    };
    Enums: {
      app_role: "owner" | "admin" | "member";
      attempt_result:
        | "no_answer"
        | "busy"
        | "switched_off"
        | "not_reachable"
        | "rejected"
        | "wrong_number"
        | "connected"
        | "wa_sent"
        | "wa_replied"
        | "not_on_whatsapp";
      connect_outcome:
        | "interested"
        | "call_later"
        | "not_interested"
        | "do_not_call"
        | "wrong_person"
        | "language_barrier"
        | "call_dropped"
        | "still_deciding"
        | "quote_accepted"
        | "quote_revision"
        | "quote_rejected";
      contact_channel: "call" | "whatsapp";
      lead_source: "manual" | "website_callback" | "website_query" | "import";
      lead_stage:
        | "new"
        | "attempting"
        | "connected"
        | "interested"
        | "callback"
        | "meeting"
        | "quotation"
        | "negotiation"
        | "won"
        | "lost"
        | "nurture"
        | "dnc";
      lost_reason:
        | "using_other_agency"
        | "budget"
        | "no_need_now"
        | "not_decision_maker"
        | "bad_past_experience"
        | "price"
        | "scope"
        | "chose_competitor"
        | "no_response"
        | "invalid_contact"
        | "other";
      meeting_mode: "phone" | "video" | "in_person";
      quote_status: "sent" | "accepted" | "rejected" | "revised";
      task_status: "open" | "done" | "cancelled";
      task_type:
        | "callback"
        | "meeting"
        | "follow_up"
        | "quote_follow_up"
        | "retry_call"
        | "re_engage"
        | "nurture";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      app_role: ["owner", "admin", "member"],
      attempt_result: [
        "no_answer",
        "busy",
        "switched_off",
        "not_reachable",
        "rejected",
        "wrong_number",
        "connected",
        "wa_sent",
        "wa_replied",
        "not_on_whatsapp",
      ],
      connect_outcome: [
        "interested",
        "call_later",
        "not_interested",
        "do_not_call",
        "wrong_person",
        "language_barrier",
        "call_dropped",
        "still_deciding",
        "quote_accepted",
        "quote_revision",
        "quote_rejected",
      ],
      contact_channel: ["call", "whatsapp"],
      lead_source: ["manual", "website_callback", "website_query", "import"],
      lead_stage: [
        "new",
        "attempting",
        "connected",
        "interested",
        "callback",
        "meeting",
        "quotation",
        "negotiation",
        "won",
        "lost",
        "nurture",
        "dnc",
      ],
      lost_reason: [
        "using_other_agency",
        "budget",
        "no_need_now",
        "not_decision_maker",
        "bad_past_experience",
        "price",
        "scope",
        "chose_competitor",
        "no_response",
        "invalid_contact",
        "other",
      ],
      meeting_mode: ["phone", "video", "in_person"],
      quote_status: ["sent", "accepted", "rejected", "revised"],
      task_status: ["open", "done", "cancelled"],
      task_type: [
        "callback",
        "meeting",
        "follow_up",
        "quote_follow_up",
        "retry_call",
        "re_engage",
        "nurture",
      ],
    },
  },
} as const;

// ── Convenience aliases (hand-written; keep below the generated block) ──
type PublicEnums = Database['public']['Enums'];
type PublicTables = Database['public']['Tables'];
export type AppRole = PublicEnums['app_role'];
export type LeadStage = PublicEnums['lead_stage'];
export type LeadSource = PublicEnums['lead_source'];
export type LostReason = PublicEnums['lost_reason'];
export type TaskType = PublicEnums['task_type'];
export type TaskStatus = PublicEnums['task_status'];
export type MeetingMode = PublicEnums['meeting_mode'];
export type QuoteStatus = PublicEnums['quote_status'];
export type ContactChannel = PublicEnums['contact_channel'];
export type AttemptResult = PublicEnums['attempt_result'];
export type ConnectOutcome = PublicEnums['connect_outcome'];
export type Profile = PublicTables['profiles']['Row'];
export type Lead = PublicTables['leads']['Row'];
export type LeadContact = PublicTables['lead_contacts']['Row'];
export type LeadPhone = PublicTables['lead_phones']['Row'];
export type LeadTask = PublicTables['lead_tasks']['Row'];
export type CallLog = PublicTables['call_logs']['Row'];
export type Quotation = PublicTables['quotations']['Row'];
export type LeadActivity = PublicTables['lead_activities']['Row'];
export type InboundEnquiry = PublicTables['inbound_enquiries']['Row'];
export type CrmSettings = PublicTables['crm_settings']['Row'];
